# This is ESPHome configuration file. This goes to the esphome folder
# You need to provide your WiFi ssis/password and passwords for API and OTA (or put them in your esphome/secrets.yaml)
esphome:
  name: meteodisplay
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.189.52

api:
  password: !secret api_password

ota:
  password: !secret ota_password

logger:
  baud_rate: 0     # Disable UART logging (pins GPIO1/3 are used for Nextion communication)

uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 115200

time:
  - platform: sntp
    id: sntp_time

sensor:
  - platform: homeassistant
    id: sun_elevation
    entity_id: sensor.sun_elevation
  - platform: homeassistant   # Teplota pocitova
    id: temperature_pocitova
    entity_id: sensor.venku_teplota_pocitova_vitr
  - platform: homeassistant   # Teplota venku
    id: temperature_outside    
    entity_id: sensor.venku_teplomer_temperature
  - platform: homeassistant   # Teplota koupelna
    id: temperature_koupelna
    entity_id: sensor.koupelna_teplomer_temperature
  - platform: homeassistant   # Dnes ikona počasí
    id: dnes_icon
    entity_id: sensor.dnes_pocasi_ikona
  - platform: homeassistant   # Měsíc ikona 
    id: mesic_icon
    entity_id: sensor.mesic_ikona
  - platform: homeassistant   # Zítra min teplota
    id: today_min
    entity_id: sensor.zitra_min
  - platform: homeassistant   # Zítra max teplota
    id: today_max
    entity_id: sensor.zitra_max
  - platform: homeassistant   # Zítra déšť
    id: today_rain
    entity_id: sensor.zitra_dest
  - platform: homeassistant   # Zítra ikona počasí
    id: zitra_icon
    entity_id: sensor.zitra_pocasi_ikona
  - platform: homeassistant   # Pozítří ikona počasí
    id: pozitri_icon
    entity_id: sensor.pozitri_pocasi_ikona
  - platform: homeassistant   # Popozítří ikona počasí
    id: popozitri_icon
    entity_id: sensor.popozitri_pocasi_ikona
  - platform: homeassistant   # Pozítří min teplota
    id: pozitri_min
    entity_id: sensor.pozitri_min
  - platform: homeassistant   # Pozítří max teplota
    id: pozitri_max
    entity_id: sensor.pozitri_max
  - platform: homeassistant   # Popozítří min teplota
    id: popozitri_min
    entity_id: sensor.popozitri_min
  - platform: homeassistant   # Popozítří max teplota
    id: popozitri_max
    entity_id: sensor.popozitri_max

text_sensor:
  - platform: homeassistant   # Pozítří
    id: pozitri
    entity_id: sensor.pozitri
  - platform: homeassistant   # Popozítří
    id: popozitri
    entity_id: sensor.popozitri

binary_sensor:
  - platform: homeassistant
    id: somebody_home
    entity_id: binary_sensor.nekdo_doma

globals:
  - id: page_id
    type: int
    restore_value: no
  - id: current_brightness             # Is display on?
    type: float
    restore_value: no
    initial_value: '-1.0'
   
display:
  - platform: nextion
    id: teplomer
    update_interval: 5s
    lambda: |-      
      // Turn display on when somebody is home. Only update when display on.
      float br;
      if (id(somebody_home).state) {   
        if (id(sun_elevation).state > 0) {
          // Full brightness during the day
          br=1.0;    
        } else {
          // 50 percent at night
          br=0.5;
        }

        if (id(page_id) == 0) {
          it.goto_page("forecast");
          it.send_command_printf("%s.pic=%.0f", "weather",id(zitra_icon).state);
          it.set_component_text_printf("minmax","%.0f/%.0f",id(today_min).state,id(today_max).state);
          if (isnan(id(today_rain).state)) {
            it.set_component_text("rain","-");
          } else {
            it.set_component_text_printf("rain","%.0f",id(today_rain).state);
          }
          auto time = id(sntp_time).now();
          it.set_component_text_printf("hour","%02d",time.hour);
          it.set_component_text_printf("minute","%02d",time.minute);
          id(page_id) +=1;
        } else if (id(page_id) == 1) {
          it.goto_page("predpoved");
          it.set_component_text("den2",id(pozitri).state.c_str());
          it.set_component_text("den3",id(popozitri).state.c_str());
          it.send_command_printf("%s.pic=%.0f", "pozitripocasi",id(pozitri_icon).state);
          it.send_command_printf("%s.pic=%.0f", "popopocasi",id(popozitri_icon).state);
          it.set_component_text_printf("pozitriden","%2.1f",id(pozitri_max).state);
          it.set_component_text_printf("pozitrinoc","%2.1f",id(pozitri_min).state);
          it.set_component_text_printf("popozitriden","%2.1f",id(popozitri_max).state);
          it.set_component_text_printf("popozitrinoc","%2.1f",id(popozitri_min).state);
          id(page_id) +=1;
        } else {
          it.goto_page("temperature");
          it.set_component_text_printf("venku","%2.1f",id(temperature_outside).state);
          it.set_component_text_printf("pocitova","%2.1f",id(temperature_pocitova).state);
          it.set_component_text_printf("koupelna","%2.1f",id(temperature_koupelna).state);
          it.send_command_printf("%s.pic=%.0f", "mesic",id(mesic_icon).state);
          it.send_command_printf("%s.pic=%.0f", "dnesni",id(dnes_icon).state);
          id(page_id) = 0;
        }
      } else {
        // Turn off the display if nobody is home. 
        br=0.0;
      }

     
      // Change brightnes if it needs to be changed
      if (id(current_brightness)!=br) {  
        it.set_backlight_brightness(br);
        id(current_brightness)=br;
      }
